### ISSUE TITLE
slide-home.php Include files with HTML should not be based on echoing strings

### ISSUE THREAD

**Issue by danialbleile** [washingtonstateuniversity/CAHNRSWP-Theme-Events#11]
As we discussed in our training, include files (if possible) should be primarily html with place holder variables for dynamically written content. 
Example
do: `<div class="promo-title"><?php echo $title;?></div>` 
don't: <?php echo '<div class="promo-title">'  . $title . '</div>';  ?>

**Comment by dwpierce** [comment]
Changed include files to match this format.
