### ISSUE TITLE
Page Slide

### ISSUE THREAD

**Issue by danialbleile** [washingtonstateuniversity/CAHNRSWP-Theme-Events#7]
Page Slide is not functioning as specified

**Comment by danialbleile** [comment]
From our discussion earlier today try this approach with the slideshow.

(php)
- Use ID's in WP nav to match nav items to page slides.
- On slide
  -- Output page slug as a data attribute or a class to connect with nav

(js)
- Prevent default on nav click
- Get id from nav
- find slide with that id
- find slug from slide
- write slug to url as hash
- do slide
- set nav to active

**Comment by dwpierce** [comment]
I have a semi functioning slider working 

Prevent default on nav click - done
Get id from nav - done
find slide with that id - found data-id and shows the slide
find slug from slide - I made the have the id= hold the slug

**Comment by dwpierce** [comment]
Finished the following:
- write slug to url as hash
- do slide
- set nav to active

On to the sliding functions.
